### ISSUE TITLE
src/httpd/http_route.c:38:5: error: implicit declaration of function 'tk_strncpy' is invalid in C99

### ISSUE THREAD

**Issue by suzp1984** [zlgopen/awtk-restful-httpd#1]
# [ENV]
Mac OS

# [Compiler Error]

src/httpd/http_route.c:38:5: error: implicit declaration of function 'tk_strncpy' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    tk_strncpy(url, c->url, len);

# [Reason]

forget to include "tkc/utils.h" in src/httpd/http_route.c

# [patch]

[http_route.patch.txt](https://github.com/zlgopen/awtk-restful-httpd/files/5324751/http_route.patch.txt)

git apply [above patch file]

**Comment by xianjimli** [comment]
合并了，谢谢你。
